apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: mapit-prod
spec:
  nodeSelector: {}
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/siamaksade/devnation-cicd-demo'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile-prod-rollback
    type: JenkinsPipeline